apiVersion: opster.opster.io/v1alpha1
kind: Es
metadata:
  name: opster-opensearch
  namespace: operator-os
  finalizers:
    - idan
spec:
  general:
    clusterName: os-from-operator
    esPort: 9200
    vendor: opensearch
    version: latest
    serviceName: es-svc
  masters:
    replicas: 3
    diskSize: 30
    NodeSelector:
    cpu: 4
    memory: 16
  nodes:
    replicas: 3
    diskSize: 100
    NodeSelector:
    cpu: 4
    memory: 16
    ingest: "true"

