apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      majorVersion: "1"
      meta.helm.sh/release-name: opensearch
      meta.helm.sh/release-namespace: opensearch-test
    creationTimestamp: "2021-10-24T09:40:26Z"
    generation: 1
    labels:
      app.kubernetes.io/component: opensearch-cluster-test-master
      app.kubernetes.io/instance: opensearch
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 1.0.0
      helm.sh/chart: opensearch-1.2.0
    name: opensearch-cluster-test-master
    namespace: opensearch-test
    resourceVersion: "301746072"
    selfLink: /apis/apps/v1/namespaces/opensearch-test/statefulsets/opensearch-cluster-test-master
    uid: 71f125e9-0128-4940-9fdb-c71995ab1108
  spec:
    podManagementPolicy: Parallel
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: opensearch
        app.kubernetes.io/name: opensearch
    serviceName: opensearch-cluster-test-master-headless
    template:
      metadata:
        annotations:
          configchecksum: 263735481e89ddf916bbc8199bdaf33dbac708c31df776f027b31d0116e7ccd
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: opensearch-cluster-test-master
          app.kubernetes.io/instance: opensearch
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: opensearch
          app.kubernetes.io/version: 1.0.0
          helm.sh/chart: opensearch-1.2.0
        name: opensearch-cluster-test-master
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - opensearch
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - opensearch
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: node.name
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: opensearch-cluster-test-master-0,opensearch-cluster-test-master-1,opensearch-cluster-test-master-2,
          - name: discovery.seed_hosts
            value: opensearch-cluster-master-headless
          - name: cluster.name
            value: opensearch-cluster-test
          - name: network.host
            value: 0.0.0.0
          - name: OPENSEARCH_JAVA_OPTS
            value: -Xmx512M -Xms512M
          - name: node.data
            value: "true"
          - name: node.ingest
            value: "true"
          - name: node.master
            value: "true"
          - name: node.remote_cluster_client
            value: "true"
          image: opensearchproject/opensearch:1.0.0
          imagePullPolicy: IfNotPresent
          name: opensearch
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: 100Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: opensearch-cluster-test-master
          - mountPath: /usr/share/opensearch/config/opensearch.yml
            name: config
            subPath: opensearch.yml
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        initContainers:
        - args:
          - chown -R 1000:1000 /usr/share/opensearch/data
          command:
          - sh
          - -c
          image: busybox:latest
          imagePullPolicy: Always
          name: fsgroup-volume
          resources: {}
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: opensearch-cluster-test-master
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 120
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-cluster-test-master-config
          name: config
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: opensearch-cluster-test-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    collisionCount: 0
    currentReplicas: 3
    currentRevision: opensearch-cluster-test-master-698f64b6d6
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
    updateRevision: opensearch-cluster-test-master-698f64b6d6
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
