apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  general:
    serviceName: opensearch-cluster
    setVMMaxMapCount: true
    version: 2.4.1
    pluginsList: []
  dashboards:
    enable: true
    version: 2.4.1
    replicas: 1
    pluginsList:
      - alertingDashboards
  nodePools:
  - component: masters
    replicas: 3
    diskSize: "1Gi"
    additionalConfig:
      key: value
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1024Mi"
    roles:
      - "data"
      - "cluster_manager"
    persistence:
      emptyDir: {}
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true