apiVersion: opster.os-operator.opster.io/v1
kind: Os
metadata:
  name: opster-opensearch
  namespace: operator-os
  finalizers:
    - Opster
spec:
  general:
    clusterName: os-from-operator
    httpPort: 9200
    vendor: opensearch
    version: latest
    serviceName: es-svc
  osDashboards:
    enable: true
  osConfMgmt: {}
  nodePools:
    - compenent: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      cpu: 4
      memory: 16
      ingest: "false"
    - compenent: nodes
      replicas: 3
      diskSize: 100
      NodeSelector:
      cpu: 4
      memory: 16
      ingest: "true"
    - compenent: coordinators
      replicas: 3
      diskSize: 100
      NodeSelector:
      cpu: 4
      memory: 16
      ingest: "false"
