# permissions for end users to view es.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-viewer-role
rules:
- apiGroups:
  - opster.opster.io
  resources:
  - es
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opster.opster.io
  resources:
  - es/status
  verbs:
  - get
