
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opster.opster.io
  resources:
  - es
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opster.opster.io
  resources:
  - es/finalizers
  verbs:
  - update
- apiGroups:
  - opster.opster.io
  resources:
  - es/status
  verbs:
  - get
  - patch
  - update
