name: Release Charts

on:
  push:
    tags:
      - 'helm-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Update chart version
        run: |
          VERSION=${GITHUB_REF//refs\/tags\/helm-}
          sed -i '' -e 's/^version.*/version: $RELEASE_VERSION/' charts/opensearch-operator/Chart.yaml
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add ../charts/opensearch-operator/Chart.yaml
          git commit -m "Update helm chart for new operator's version release ${RELEASE_VERSION}"
          git push
      # See https://github.com/helm/chart-releaser
      # See https://github.com/helm/chart-releaser-action
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
